FROM ghcr.io/contrast-security-inc/go-agent:latest AS builder
ARG FRAMEWORK=std

WORKDIR /build
COPY . .

# Build the binary
RUN go build -ldflags='-w -s -extldflags "-static"' -o app ./cmd/${FRAMEWORK}

# Create /etc/passwd to help showcase path traversal vulnerability.
RUN echo "root:x:0:0:root:/root:/bin/bash" >> ./fakepasswd && \
    echo "catty:x:42:42:boh:/etc/contrastsecurity:/bin/bash" >> ./fakepasswd

# Move the finished build to a scratch container
FROM scratch

# Copy the testbench to the new scratch container
COPY --from=builder /build/views ./views
COPY --from=builder /build/public ./public
COPY --from=builder /build/app ./app
COPY --from=builder /build/fakepasswd /etc/passwd

# Execute the testbench agent
ENTRYPOINT ["./app", "-addr=:8080"]