version: '3.7'
services:
  std:
    build: .
    ports:
      - '8080:8080'
  gin:
    build:
      context: .
      args:
        FRAMEWORK: gin
    ports:
      - '8080:8080'
  julienschmidt:
    build:
      context: .
      args:
        FRAMEWORK: julienschmidt
    ports:
      - '8080:8080'
