ARG GO_VERSION=latest
FROM golang:${GO_VERSION} AS builder

WORKDIR /build

COPY . .

# Install contrast-go
RUN go run github.com/contrast-security-oss/contrast-go-installer@latest latest

# Build the app with contrast-go
ARG FRAMEWORK=std
RUN CGO_ENABLED=0 contrast-go build -o go-test-bench ./cmd/${FRAMEWORK}

# Move the finished build to a more minimal container
FROM alpine:latest
COPY --from=builder /build/views ./views
COPY --from=builder /build/public ./public
COPY --from=builder /build/go-test-bench ./go-test-bench

# Copy over the Contrast configuration file. All configuration can be done with
# environment variables as well. See our docs for more details:
#
# https://docs.contrastsecurity.com/en/go-configuration.html
COPY ./contrast_security.yaml .

ENTRYPOINT ["./go-test-bench", "-addr=:8080"]
